ETFest/src/java/adminControllers/AdminHomeController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminControllers;

import entity.Festival;
import entity.Reservation;
import java.io.Serializable;
import java.util.Calendar;
import static java.util.Calendar.YEAR;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.CriteriaSpecification;
import org.hibernate.criterion.Order;
import org.chartistjsf.model.chart.AspectRatio;
import org.chartistjsf.model.chart.BarChartModel;
import org.chartistjsf.model.chart.BarChartSeries;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Petar
 */
public class AdminHomeController implements Serializable {

    private BarChartModel barModelViews;
    private BarChartModel barModelTickets;

    private Map<Integer, Integer> festivalTickets;
    private List<Festival> topViewed;
    private List<Festival> topTickets;

    /**
     * Creates a new instance of AdminHomeController
     */
    public AdminHomeController() {
        Session session = null;
        Transaction tx = null;
        try {
            session = util.HibernateUtil.getSessionFactory().openSession();
            tx = session.beginTransaction();

            topViewed = session.createCriteria(Festival.class)
                    .setResultTransformer(CriteriaSpecification.DISTINCT_ROOT_ENTITY)
                    .add(Restrictions.eq("canceled", false))
                    .addOrder(Order.desc("views"))
                    .list();

            topViewed = (topViewed.size() > 5 ? topViewed.subList(0, 5) : topViewed);

            topTickets = session.createCriteria(Festival.class)
                    .setResultTransformer(CriteriaSpecification.DISTINCT_ROOT_ENTITY)
                    .add(Restrictions.eq("canceled", false))
                    .list();
            topTickets = filterByTickets(topTickets, session);

            createBarModelViews(topViewed);
            createModelTickets(topTickets);
        } catch (HibernateException ex) {

        } catch (Exception ex) {

        } finally {
            if (null != tx) {
                tx.commit();
            }
            if (null != session) {
                session.close();
            }
        }
    }

    public BarChartModel getBarModelViews() {
        return barModelViews;
    }

    public BarChartModel getBarModelTickets() {
        return barModelTickets;
    }

    private List<Festival> filterByTickets(List<Festival> topTickets, Session session) {
        festivalTickets = new HashMap<>();
        topTickets.forEach((fest) -> {
            List<Reservation> purchasedReservations = session.createCriteria(Reservation.class).setResultTransformer(CriteriaSpecification.DISTINCT_ROOT_ENTITY)
                    .add(Restrictions.eq("festival", fest))
                    .add(Restrictions.eq("purchased", true))
                    .list();

            int total = 0;
            total = purchasedReservations.stream().map((res) -> res.getNumOfTickets()).reduce(total, Integer::sum);
            festivalTickets.put(fest.getId(), total);
        });

        topTickets.sort((o1, o2) -> {
            Festival fest1 = (Festival) o1;
            Festival fest2 = (Festival) o2;

            return festivalTickets.get(fest2.getId()) - festivalTickets.get(fest1.getId());
        });

        if (topTickets.size() > 5) {
            return topTickets.subList(0, 5);
        } else {
            return topTickets;
        }
    }

    private void createModelTickets(List<Festival> festivals) {
        barModelTickets = initBarModelTickets(festivals);
    }

    private void createBarModelViews(List<Festival> festivals) {
        barModelViews = initBarModelViews(festivals);
    }

    private BarChartModel initBarModelViews(List<Festival> festivals) {
        BarChartModel model = new BarChartModel();
        model.setAspectRatio(AspectRatio.GOLDEN_SECTION);
        model.addLabel("Festival");
        final Calendar cal = Calendar.getInstance();
        festivals.forEach((fest) -> {
            cal.setTime(fest.getStartDate());
            BarChartSeries series = new BarChartSeries();
            series.setName(fest.getName() + " " + cal.get(YEAR));
            series.set(fest.getViews());

            model.addSeries(series);
        });

        model.setShowTooltip(true);
        model.setSeriesBarDistance(30);
        model.setAnimateAdvanced(true);

        return model;
    }

    private BarChartModel initBarModelTickets(List<Festival> festivals) {
        BarChartModel model = new BarChartModel();
        model.setAspectRatio(AspectRatio.GOLDEN_SECTION);
        model.addLabel("Festival");
        final Calendar cal = Calendar.getInstance();
        festivals.forEach((fest) -> {
            cal.setTime(fest.getStartDate());
            BarChartSeries series = new BarChartSeries();
            series.setName(fest.getName() + " " + cal.get(YEAR));
            series.set(festivalTickets.get(fest.getId()));

            model.addSeries(series);
        });

        model.setShowTooltip(true);
        model.setSeriesBarDistance(30);
        model.setAnimateAdvanced(true);

        return model;
    }

    public List<Festival> getTopViewed() {
        return topViewed;
    }

    public List<Festival> getTopTickets() {
        return topTickets;
    }

    public String getYear(Festival fest){
        Calendar cal = Calendar.getInstance();
        cal.setTime(fest.getStartDate());
        return String.valueOf(cal.get(Calendar.YEAR));
    }
    
    public int getTickets(Festival fest){
        return festivalTickets.get(fest.getId());
    }
}

ETFest/src/java/adminControllers/ImportFestivalController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminControllers;

import dataModels.FestivalModel;
import dataModels.FestivalScheduleModel;
import entity.SocialLink;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.stream.Collectors;
import javax.faces.application.FacesMessage;
import static javax.faces.application.FacesMessage.SEVERITY_ERROR;
import static javax.faces.application.FacesMessage.SEVERITY_WARN;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import util.CSVParser;
import util.FileParseException;
import util.JsonParser;

/**
 *
 * @author Petar
 */
@Named
@SessionScoped
public class ImportFestivalController implements Serializable {

    private UploadedFile currentFile;
    private FestivalModel model;
    private FestivalScheduleModel previewScheduleModel;

    @ManagedProperty(value = "#{addFestivalController}")
    private AddFestivalController addFestivalController;

    /**
     * Creates a new instance of ImportFestivalController
     */
    public ImportFestivalController() {
    }

    public void upload(FileUploadEvent event) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.getExternalContext().getFlash().setKeepMessages(true);

        this.currentFile = event.getFile();

        if (!(currentFile.getFileName().endsWith("csv") || currentFile.getFileName().endsWith("json"))) {
            context.addMessage(null, new FacesMessage(SEVERITY_WARN, "Warning", "Only .csv and .json files allowed"));
            return;
        }
        try {
            if (currentFile.getFileName().endsWith("csv")) {
                model = new CSVParser(currentFile).parse();
            } else {
                model = new JsonParser(currentFile).parse();
            }
            context.getApplication().getNavigationHandler().handleNavigation(context, null, "importedFestivalGallery?faces-redirect=true");
        } catch (FileParseException ex) {
            context.addMessage(null, new FacesMessage(SEVERITY_ERROR, "Error", ex.getMessage()));
        }
    }

    public void filePreview(FileUploadEvent event) {
        model.setCurrentFile(event.getFile());
        model.setPendingUpload(event.getFile());
        model.saveFilePreviewContents();
    }

    public void previewImage() {
        model.saveFilePreviewContents();
    }

    public void addFile() {
        if (model.getPendingUpload() == null) {
            return;
        }
        boolean ok = true;
        UploadedFile file = model.getPendingUpload();
        if (file.getContentType().startsWith("video")) {
            String type = file.getContentType().split("/")[1];
            switch (type) {
                case "mp4":
                case "webm":
                case "ogg":
                    break;
                default:
                    ok = false;
            }

            if (!ok) {
                FacesContext context = FacesContext.getCurrentInstance();
                context.addMessage(null, new FacesMessage(SEVERITY_WARN, "Warning", "Supported video types: mp4, webm, ogg"));
                context.getExternalContext().getFlash().setKeepMessages(true);
                return;
            }
        } else {
            if (file.getSize() > 16777215) {
                FacesContext context = FacesContext.getCurrentInstance();
                context.addMessage(null, new FacesMessage(SEVERITY_WARN, "Warning", "Maximal image size iz 16MB"));
                context.getExternalContext().getFlash().setKeepMessages(true);
                return;
            }
        }

        model.getUploadedFiles().add(model.getPendingUpload());
        model.setCurrentFile(null);
        model.setPendingUpload(null);
    }

    public void removeFile() {
        model.getUploadedFiles().remove(model.getCurrentFile());
        model.setCurrentFile(null);
    }

    public void preview() {
        addFestivalController.setErrorMessage("");
        previewScheduleModel = new FestivalScheduleModel(model.getPerformances(), model.getStartDate(), model.getEndDate());
        FacesContext context = FacesContext.getCurrentInstance();
        context.getApplication().getNavigationHandler().handleNavigation(context, null, "preview?faces-redirect=true");
    }

    public String viewImageContents(UploadedFile file) {
        return Base64.getEncoder().encodeToString(file.getContents());
    }

    public void save() {
        addFestivalController.setModel(model);
        addFestivalController.save();
    }

    public UploadedFile getCurrentFile() {
        return currentFile;
    }

    public void setCurrentFile(UploadedFile currentFile) {
        this.currentFile = currentFile;
    }

    public AddFestivalController getAddFestivalController() {
        return addFestivalController;
    }

    public void setAddFestivalController(AddFestivalController addFestivalController) {
        this.addFestivalController = addFestivalController;
    }

    public FestivalModel getModel() {
        return model;
    }

    public void setModel(FestivalModel model) {
        this.model = model;
    }

    public FestivalScheduleModel getPreviewScheduleModel() {
        return previewScheduleModel;
    }

    public void setPreviewScheduleModel(FestivalScheduleModel previewScheduleModel) {
        this.previewScheduleModel = previewScheduleModel;
    }

    public List<SocialLink> getSocialLinks() {
        List<SocialLink> links = new ArrayList<>();
        model.getSocialMediaLinks().forEach((t, u) -> {
            links.add(new SocialLink(null, t, u));
        });
        return links;
    }

    public void setDummy(String dummy) {

    }

    public String getDummy() {
        return String.valueOf(1);
    }

    public List<UploadedFile> getImages() {
        return model.getUploadedFiles().stream().filter((f) -> f.getContentType().startsWith("image")).collect(Collectors.toList());
    }
}

ETFest/src/java/userControllers/UserFileUploadController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userControllers;

import adminControllers.AddFestivalController;
import entity.Festival;
import entity.File;
import entity.Reservation;
import entity.User;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Calendar;
import java.util.List;
import java.util.stream.Collectors;
import javax.faces.application.FacesMessage;
import static javax.faces.application.FacesMessage.SEVERITY_ERROR;
import static javax.faces.application.FacesMessage.SEVERITY_WARN;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author Petar
 */
public class UserFileUploadController implements Serializable {

    private UploadedFile currentFile;
    private byte[] filePreviewContents;
    private static final long VIDEO_SIZE_LIMIT = 100 * 1024 * 1024;

    /**
     * Creates a new instance of UserFileUploadController
     */
    public UserFileUploadController() {
    }

    public UploadedFile getCurrentFile() {
        return currentFile;
    }

    public void setCurrentFile(UploadedFile currentFile) {
        this.currentFile = currentFile;
    }

    public void preview(FileUploadEvent event) {
        setCurrentFile(event.getFile());
        if (null != currentFile) {
            filePreviewContents = currentFile.getContents();
        }
    }

    public String getFilePreviewContents() {
        return Base64.getEncoder().encodeToString(filePreviewContents);
    }

    public void upload() {
        FacesContext context = FacesContext.getCurrentInstance();
        context.getExternalContext().getFlash().setKeepMessages(true);

        if (null == currentFile) {
            context.addMessage(null, new FacesMessage(SEVERITY_WARN, "Warning", "You must choose a file to upload"));
            return;
        }

        Session session = null;
        Transaction tx = null;
        try {
            HttpSession httpSession = (HttpSession) context.getExternalContext().getSession(true);
            User currentUser = (User) httpSession.getAttribute("currentUser");
            Festival festival = (Festival) httpSession.getAttribute("currentFestival");
            if (null == currentUser || null == festival) {
                return;
            }
            session = util.HibernateUtil.getSessionFactory().openSession();
            tx = session.beginTransaction();
            session.refresh(currentUser);

            List<Reservation> purchases = (new ArrayList<>(currentUser.getReservations()))
                    .stream().filter((res) -> res.isPurchased() && res.getFestival().getId().equals(festival.getId()))
                    .collect(Collectors.toList());

            if (purchases.isEmpty()) {
                context.addMessage(null, new FacesMessage(SEVERITY_WARN, "Warning", "You cannot upload if you haven't purchased a ticket for this festival!"));
                tx.commit();
                return;
            }

            util.FileUtil.persistFile(session, festival, currentFile, currentUser);
            tx.commit();
            session.flush();
            context.addMessage(null, new FacesMessage("Success", "Your uploaded file is pending approval"));
        } catch (HibernateException ex) {
            context.addMessage(null, new FacesMessage(SEVERITY_ERROR, "Error", "Something went wrong, please try again"));
            if(null != tx){
                tx.rollback();
            }
        } finally {
            if (null != session) {
                session.close();
            }
        }
    }


    public String getCurrentFileName() {
        if (null != currentFile) {
            return currentFile.getFileName();
        }
        return "";
    }

    public boolean isCurrentFileVideo() {
        return null != currentFile && currentFile.getContentType().startsWith("video");
    }

}

ETFest/web/addFestivalGallery.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title></title>
    </h:head>
    <h:body>
        <ui:composition template="templates/adminLayout.xhtml">
            <ui:define name="windowTitle">
                Add gallery
            </ui:define>
            <h:form>
                <p:remoteCommand name="onload" action="#{addFestivalController.goToStep(1)}" autoRun="true" />
            </h:form>
            <ui:define name="content">
                <style>
                    .ui-fileupload-filename {
                        /*word-break: break-all !important;*/
                        display: inline-block;
                        overflow: hidden !important;
                        max-width: 150px;
                        text-overflow: ellipsis;
                        white-space: nowrap;
                    }
                </style>
                <h2 style="text-align: center; margin:auto; margin-bottom: 20px"> Add new festival</h2>
                <h:panelGroup class="ui-fluid" style="margin: auto; max-width: 800px" id="steps">
                    <h:form id="stepsForm">
                        <p:steps activeIndex="2" styleClass="customSteps" readonly="false">
                            <p:menuitem value="#{addFestivalController.getStep(0)}"
                                        url="addFestivalBasicInfo.xhtml"
                                        ajax="false"/>
                            <p:menuitem value="#{addFestivalController.getStep(1)}"
                                        url="addFestivalSchedule.xhtml"
                                        ajax="false"/>
                            <p:menuitem value="#{addFestivalController.getStep(2)}"
                                        url="addFestivalGallery.xhtml"
                                        ajax="false"/>
                        </p:steps>
                    </h:form>
                </h:panelGroup>
                <h:panelGroup id="thirdStep" class="ui-fluid addFestStep" >
                    <h3 class="centerItem" style="margin-top: 80px;"> Gallery </h3>
                    <hr class="centerItem" style="margin-bottom: 20px;"/>
                    <div class="ui-g centerItem">
                        <p:outputLabel id="globalErrorMessageLevelThree" value="#{addFestivalController.errorMessage}" styleClass="errorMessage"/>
                        <h:form id="fileUploadForm" enctype="multipart/form-data" style="width:100%">
                            <div class="ui-g" style="width:100%">
                                <div class="ui-g-12 ui-md-3 ui-lg-3">
                                    <div class="ui-g-12">
                                        <p:fileUpload value="#{addFestivalController.model.currentFile}" auto="true" skinSimple="true"
                                                      update="fileUploadForm:filePreview"
                                                      fileUploadListener="#{addFestivalController.preview}"/>
                                    </div>
                                    <div class="ui-g-12">
                                        <p:commandButton value="Add" action="#{addFestivalController.addFile()}" update="@(.updateableTable) menuForm:messages"
                                                         oncomplete="removeExtraTable()"/>
                                    </div>

                                    <div class="ui-g-12">
                                        <p:commandButton value="Finish" actionListener="#{addFestivalController.save()}" update="@(.errorMessage)"/>
                                    </div>
                                </div>
                                <h:panelGroup class="ui-g-12 ui-md-9 ui-lg-9" id="filePreview">
                                    <p:outputLabel value="#{addFestivalController.model.currentFileName()}" rendered="#{addFestivalController.model.currentFileVideo}"/>
                                    <ui:fragment rendered="#{not addFestivalController.model.currentFileVideo and not empty addFestivalController.model.currentFile}">
                                        <img src="data:image/png;base64,#{addFestivalController.model.filePreviewContents}" style="max-height: 200px; max-width: 500px"/>
                                    </ui:fragment>
                                </h:panelGroup>
                            </div>
                        </h:form>  

                        <h:form id="form">
                            <p:dataTable id="uploadedFileTable" var="currentFile" value="#{addFestivalController.model.uploadedFiles}"
                                         selection="#{addFestivalController.model.currentFile}" selectionMode="single" stickyHeader="false"
                                         rowKey="#{currentFile.fileName}-#{currentFile.contentType}-#{currentFile.size}"
                                         class="updateableTable">                            
                                <p:column headerText="File name">
                                    <h:outputText value="#{currentFile.fileName}"/>
                                </p:column>
                                <p:column headerText="Type">
                                    <h:outputText value="#{currentFile.contentType}"/>
                                </p:column>
                                <p:column headerText="Size">
                                    <h:outputText value="#{currentFile.size / 1024} KB"/>
                                </p:column>
                            </p:dataTable>
                            <p:contextMenu for="uploadedFileTable">
                                <p:menuitem value="Preview" action="#{addFestivalController.previewImage()}" update="fileUploadForm:filePreview"/>
                                <p:menuitem value="Delete" update="uploadedFileTable" icon="ui-icon-close" actionListener="#{addFestivalController.removeFile()}"
                                            oncomplete="removeExtraTable()"/>
                            </p:contextMenu>
                        </h:form>
                    </div>
                </h:panelGroup>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

ETFest/web/adminSearch.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./templates/adminLayout.xhtml">

    <ui:define name="windowTitle">
        Search
    </ui:define>

    <ui:define name="content">
        <ui:include src="sections/search.xhtml"/>
    </ui:define>

</ui:composition>

ETFest/web/importedFestivalGallery.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./templates/adminLayout.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns="http://www.w3.org/1999/xhtml">

    <ui:define name="windowTitle">
        Add gallery
    </ui:define>

    <ui:define name="content">
        <style>
                    .ui-fileupload-filename {
                        /*word-break: break-all !important;*/
                        display: inline-block;
                        overflow: hidden !important;
                        max-width: 150px;
                        text-overflow: ellipsis;
                        white-space: nowrap;
                    }
                </style>
                <h2 style="text-align: center; margin:auto; margin-bottom: 20px"> Add new festival</h2>
                <h:panelGroup class="ui-fluid" style="margin: auto; max-width: 800px" id="steps">
                    <h:form id="stepsForm">
                        <p:steps activeIndex="1" readonly="true">
                            <p:menuitem value="Choose file"/>
                            <p:menuitem value="Gallery"/>
                            <p:menuitem value="Preview"/>
                        </p:steps>
                    </h:form>
                </h:panelGroup>
                <h:panelGroup id="secondStep" class="ui-fluid addFestStep" >
                    <h3 class="centerItem" style="margin-top: 80px;"> Gallery </h3>
                    <hr class="centerItem" style="margin-bottom: 20px;"/>
                    <div class="ui-g centerItem">
                        <h:form id="fileUploadForm" enctype="multipart/form-data" style="width:100%">
                            <div class="ui-g" style="width:100%">
                                <div class="ui-g-12 ui-md-3 ui-lg-3">
                                    <div class="ui-g-12">
                                        <p:fileUpload value="#{importFestivalController.model.currentFile}" auto="true" skinSimple="true"
                                                      update="fileUploadForm:filePreview"
                                                      fileUploadListener="#{importFestivalController.filePreview}"/>
                                    </div>
                                    <div class="ui-g-12">
                                        <p:commandButton value="Add" action="#{importFestivalController.addFile()}" update="@(.updateableTable) menuForm:messages"
                                                         oncomplete="removeExtraTable()"/>
                                    </div>

                                    <div class="ui-g-12">
                                        <p:commandButton value="Preview" actionListener="#{importFestivalController.preview()}" update="@(.errorMessage)"/>
                                    </div>
                                </div>
                                <h:panelGroup class="ui-g-12 ui-md-9 ui-lg-9" id="filePreview">
                                    <p:outputLabel value="#{importFestivalController.model.currentFileName()}" rendered="#{importFestivalController.model.currentFileVideo}"/>
                                    <ui:fragment rendered="#{not importFestivalController.model.currentFileVideo and not empty importFestivalController.model.currentFile}">
                                        <img src="data:image/png;base64,#{importFestivalController.model.filePreviewContents}" style="max-height: 200px; max-width: 500px"/>
                                    </ui:fragment>
                                </h:panelGroup>
                            </div>
                        </h:form>  

                        <h:form id="form">
                            <p:dataTable id="uploadedFileTable" var="currentFile" value="#{importFestivalController.model.uploadedFiles}"
                                         selection="#{importFestivalController.model.currentFile}" selectionMode="single" stickyHeader="false"
                                         rowKey="#{currentFile.fileName}-#{currentFile.contentType}-#{currentFile.size}"
                                         class="updateableTable">                            
                                <p:column headerText="File name">
                                    <h:outputText value="#{currentFile.fileName}"/>
                                </p:column>
                                <p:column headerText="Type">
                                    <h:outputText value="#{currentFile.contentType}"/>
                                </p:column>
                                <p:column headerText="Size">
                                    <h:outputText value="#{currentFile.size / 1024} KB"/>
                                </p:column>
                            </p:dataTable>
                            <p:contextMenu for="uploadedFileTable">
                                <p:menuitem value="Preview" action="#{importFestivalController.previewImage()}" update="fileUploadForm:filePreview" icon="fa fa-eye"/>
                                <p:menuitem value="Delete" update="uploadedFileTable" icon="ui-icon-close" actionListener="#{importFestivalController.removeFile()}"
                                            oncomplete="removeExtraTable()"/>
                            </p:contextMenu>
                        </h:form>
                    </div>
                </h:panelGroup>
    </ui:define>

</ui:composition>